[Icon Theme]
Name=elementary
Comment=Smooth modern theme designed to be intuitive.
Inherits=ubuntu-mono,gnome,hicolor

Example=directory-x-normal

#Directory list
Directories=actions/16,actions/22,actions/24,actions/32,actions/48,actions/64,actions/72,actions/128,places/16,places/22,places/24,places/32,places/48,places/64,places/128,mimes/16,mimes/24,mimes/32,mimes/48,mimes/128,status/16,status/22,status/24,status/32,status/48,status/64,status/128

[actions/16]
Size=16
Context=Actions
Type=Fixed

[actions/22]
Size=22
Context=Actions
Type=Fixed

[actions/24]
Size=24
Context=Actions
Type=Fixed

[actions/32]
Size=32
Context=Actions
Type=scalable

[actions/48]
Size=48
Context=Actions
Type=Scalable

[actions/64]
Size=64
Context=Actions
Type=Scalable

[actions/72]
Size=72
Context=Actions
Type=Scalable

[actions/128]
Size=128
Context=Actions
Type=Scalable

[mimes/16]
Size=16
Context=MimeTypes
Type=scalable

[mimes/22]
Size=22
Context=MimeTypes
Type=scalable

[mimes/24]
Size=24
Context=MimeTypes
Type=scalable

[mimes/32]
Size=32
Context=MimeTypes
Type=scalable

[mimes/48]
Size=48
Context=MimeTypes
Type=Scalable

[mimes/128]
Size=128
Context=MimeTypes
Type=Scalable

[places/16]
Size=16
Context=Places
Type=Fixed

[places/22]
Size=22
Context=Places
Type=Fixed

[places/24]
Size=24
Context=Places
Type=Fixed

[places/32]
Size=32
Context=Places
Type=Fixed

[places/48]
Size=48
Context=Places
Type=Scalable

[places/64]
Size=64
Context=Places
Type=Scalable

[places/128]
Size=128
Context=Places
Type=Scalable

[status/16]
Size=16
Context=Status
Type=Fixed

[status/22]
Size=22
Context=Status
Type=Fixed

[status/24]
Size=24
Context=Status
Type=Fixed

[status/32]
Size=32
Context=Status
Type=Fixed

[status/48]
Size=48
Context=Status
Type=Scalable

[status/64]
Size=64
Context=Status
Type=Scalable

[status/128]
Size=128
Context=Status
Type=Scalable
