#!/bin/bash
# killspace v0.1
# License: GPLv2
# by AZ (Aitjcize) 
#
# usage: killspace [--dry] [path]
# Present working directory is used if path is not set
# Use `--dry' to run the script without really modify the filename, this is
# useful when you want to find out which filename contains space.

# you can change the delimiter and seperator if you want.
# The only restriction for the delimiter is that it shouldn't appear in any of
# your filename.

delimiter='|DL|'
seperator='_'

# functions

killspace() {
  echo Scanning `pwd`/$1 ...
  cd "$1"
  for fn in `ls | sed "s/ /$delimiter/g"`
  do
    rfn=`echo $fn | sed "s/$delimiter/ /g"`
    cfn=`echo $fn | sed "s/$delimiter/$seperator/g"`
    if [ "$rfn" != "$cfn" ]; then
      if [ $dry == 0 ]; then
        mv "$rfn" "$cfn"
      fi
      echo -e "\033[01;36m* $rfn -> $cfn \033[00m"
    fi
    if [ -d "$cfn" ]; then
      killspace "$cfn"
    fi
  done
  cd ..
}

rechmod() {
  echo Scanning `pwd`/$1 ...
  cd "$1"
  for i in `ls`
  do
    if [ ${i#*.} == "svg" ]; then
      inkscape -f $i -e ${i%.svg}.png
      echo $i
    elif [ -d $i ]; then
      rechmod $i
    fi
  done
  cd ..
}

# main

dry=0
killspace=0
rechmod=0

if [ "$1" == "--dry" ]; then
  echo "Dry run mode."
  dry=1
  shift
fi

if [ "$1" == "rechmod" ]; then
  rechmod=1
  shift
elif [ "$1" == "killspace" ]; then
  killspace=1
  shift
fi

if [ -n "$1" ]; then
  target_dir=$1
else
  target_dir=`pwd`
fi

if [ $dry == 0 ] && [ $killspace == 1 ]; then
  echo -n "Do you want to change all space in filename to \`$seperator' in $kdir? [y/N] "
  read yn
  if [ "$yn" != "y" ] && [ "$yn" != "yes" ]; then
    exit 0
  fi
fi

if [ $killspace == 1 ]; then
  killspace $1
elif [ $rechmod == 1 ]; then
  rechmod $1
fi

# end
