#!/bin/bash
# Gummi win32 build script
# by Wei-Ning Huang
#
# You need to run this script under MSYS and with NSIS installed.
#

wd=`pwd`

dest=win32build
mkdir $dest
cp -r ../gummi $dest
cp -r ../po $dest
cp win32/Installer.nsi win32/setup.py $dest/gummi
cp $dest/gummi/docs/LICENSE $dest/gummi

# Manage translations
cd $dest/po
rm template*.po

for i in `ls *.po`; do
  mv $i ${i%-*}.po
done

for i in `ls *.po`; do
  msgfmt $i -o ${i%.po}.mo
done
cd ..

# Manage version
cd gummi
echo "What's the version number for this release?"
read rlschoice

# sed on windows does not have the -i option
sed s/svn/$rlschoice/ setup.py > setup.py2
mv setup.py2 setup.py
sed s/svn/$rlschoice/ Installer.nsi > Installer.nsi2
mv Installer.nsi2 Installer.nsi
sed s/svn/$rlschoice/ Preferences.py > Preferences.py2
mv Preferences.py2 Preferences.py

mv misc/gummi gummi.py
mv misc/gummi_256x256.ico .
mv misc/gummi_64x64.ico .

# run py2exe
python setup.py py2exe -p atk,gio,pango,pangocairo,cairo,poppler,gtksourceview2

# Copy gtk DLLs, settings
cp -r $wd/win32/GtkSettings/* $wd/win32/DLLs/*.dll dist

# Copy locales
cd $wd/win32build/po

for i in `ls *.mo`; do
  mos=../gummi/dist/share/locale/${i%.mo}/LC_MESSAGES
  echo $i
  mkdir -p $mos
  cp $i $mos
done

# Make Installer
cd ../gummi
makensis Installer.nsi
mv Gummi-$rlschoice-setup.exe $wd
